
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ANIO APELLIDO DELIMITADOR DIA ESTADO GENERAR ID MES NOMBRE NUMERO OPERADOR SEGUNDOAPELLIDO SEXO\nprograma : asignaciones GENERAR\n\nasignaciones : asignacion asignaciones\n             | asignacion\n\nasignacion : NOMBRE OPERADOR ID\n           | APELLIDO OPERADOR ID\n           | SEGUNDOAPELLIDO OPERADOR ID\n           | SEXO OPERADOR ID\n           | DIA OPERADOR NUMERO\n           | MES OPERADOR NUMERO\n           | ANIO OPERADOR NUMERO\n           | ESTADO OPERADOR ID\n'
    
_lr_action_items = {'NOMBRE':([0,3,22,23,24,25,26,27,28,29,],[4,4,-4,-5,-6,-7,-8,-9,-10,-11,]),'APELLIDO':([0,3,22,23,24,25,26,27,28,29,],[5,5,-4,-5,-6,-7,-8,-9,-10,-11,]),'SEGUNDOAPELLIDO':([0,3,22,23,24,25,26,27,28,29,],[6,6,-4,-5,-6,-7,-8,-9,-10,-11,]),'SEXO':([0,3,22,23,24,25,26,27,28,29,],[7,7,-4,-5,-6,-7,-8,-9,-10,-11,]),'DIA':([0,3,22,23,24,25,26,27,28,29,],[8,8,-4,-5,-6,-7,-8,-9,-10,-11,]),'MES':([0,3,22,23,24,25,26,27,28,29,],[9,9,-4,-5,-6,-7,-8,-9,-10,-11,]),'ANIO':([0,3,22,23,24,25,26,27,28,29,],[10,10,-4,-5,-6,-7,-8,-9,-10,-11,]),'ESTADO':([0,3,22,23,24,25,26,27,28,29,],[11,11,-4,-5,-6,-7,-8,-9,-10,-11,]),'$end':([1,12,],[0,-1,]),'GENERAR':([2,3,13,22,23,24,25,26,27,28,29,],[12,-3,-2,-4,-5,-6,-7,-8,-9,-10,-11,]),'OPERADOR':([4,5,6,7,8,9,10,11,],[14,15,16,17,18,19,20,21,]),'ID':([14,15,16,17,21,],[22,23,24,25,29,]),'NUMERO':([18,19,20,],[26,27,28,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'programa':([0,],[1,]),'asignaciones':([0,3,],[2,13,]),'asignacion':([0,3,],[3,3,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> programa","S'",1,None,None,None),
  ('programa -> asignaciones GENERAR','programa',2,'p_programa','sintacticocurp.py',253),
  ('asignaciones -> asignacion asignaciones','asignaciones',2,'p_asignaciones','sintacticocurp.py',259),
  ('asignaciones -> asignacion','asignaciones',1,'p_asignaciones','sintacticocurp.py',260),
  ('asignacion -> NOMBRE OPERADOR ID','asignacion',3,'p_asignacion','sintacticocurp.py',266),
  ('asignacion -> APELLIDO OPERADOR ID','asignacion',3,'p_asignacion','sintacticocurp.py',267),
  ('asignacion -> SEGUNDOAPELLIDO OPERADOR ID','asignacion',3,'p_asignacion','sintacticocurp.py',268),
  ('asignacion -> SEXO OPERADOR ID','asignacion',3,'p_asignacion','sintacticocurp.py',269),
  ('asignacion -> DIA OPERADOR NUMERO','asignacion',3,'p_asignacion','sintacticocurp.py',270),
  ('asignacion -> MES OPERADOR NUMERO','asignacion',3,'p_asignacion','sintacticocurp.py',271),
  ('asignacion -> ANIO OPERADOR NUMERO','asignacion',3,'p_asignacion','sintacticocurp.py',272),
  ('asignacion -> ESTADO OPERADOR ID','asignacion',3,'p_asignacion','sintacticocurp.py',273),
]
